### ISSUE TITLE
download timeout between building

### ISSUE THREAD

**Issue by zyf0330** [home-prebuilders-association/prebuild#186]
When I `npm i zeromq`, it auto builds, and shows `prebuild-install info looking for local prebuild @ prebuilds/zeromq-v4.5.0-node-v48-linux-x64.tar.gz`. But I cannot download it caused network timeout. So whether there is a way to let put the package in prebuilds before auto build?

**Comment by ralphtheninja** [comment]
@zyf0330 You can do this. Cached prebuilds end up in `~/.npm/_prebuilds`. You need to make sure the filename is correct though.

```
$ ls ~/.npm/prebuilds/
http-localhost-8890-a-native-module-v1.0.0-node-v57-linux-x64.tar.gz
https-github.com-level-leveldown-hyper-releases-download-v1.1.3-0-leveldown-hyper-v1.1.3-0-node-v57-linux-x64.tar.gz
https-github.com-level-leveldown-hyper-releases-download-v1.1.3-leveldown-hyper-v1.1.3-node-v57-linux-x64.tar.gz
https-github.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v57-linux-x64.tar.gz
https-github.com-level-rocksdb-releases-download-v1.0.0-rocksdb-v1.0.0-node-v57-linux-x64.tar.gz
https-github.com-ralphtheninja-a-native-module-releases-download-v1.0.0-a-native-module-v1.0.0-node-v57-linux-x64.tar.gz
```

The filenames are constructed by replacing via regexp, see https://github.com/home-prebuilders-association/prebuild-install/blob/master/util.js#L51

**Comment by zyf0330** [comment]
I try this, but it seems that not find this path. 
I saw it found, but not today.
It just find  looking for local prebuild

**Comment by zyf0330** [comment]
Whether because `WARN install EACCES: permission denied, access '/root/.npm'`?

**Comment by zyf0330** [comment]
It actually is! I solved now.
